# 도커 최신버전 사용 지정
version: '3'

services:
  web:
    build: . # 현재 폴더의 Dockerfile 사용
    command: python manage.py runserver 0.0.0.0:8000
    volumes: # 현재 폴더를 /usr/src/app와 연결함.
    - ./:/usr/src/app/
    ports: # 로컬과 도커의 포트 연결
    - 8000:8000
    env_file: # web 사이트의 오류 출력하지 않음
    - ./envs/.env.dev